### ISSUE TITLE
Feedback view

### ISSUE THREAD

**Issue by 0is1** [HSLdevcom/react-native-proto#25]
Test out
* microphone
* NFC
* Bluetooth (Bluetooth is actually being tested in #9)
* Camera
  * QR/many other codes are readable via [react-native-camera](https://github.com/lwansbrough/react-native-camera#onbarcoderead)

TODO: more specific description

**Comment by tuukka** [comment]
For v0.2, the use case could be this feedback system: https://www.hsl.fi/uutiset/2017/joukkoliikenteessa-kokeillaan-pikapalautetta-9712

**Comment by 0is1** [comment]
Camera works: https://github.com/HSLdevcom/react-native-proto/blob/v.0.2/app/components/Camera.js

Microphone works: https://github.com/HSLdevcom/react-native-proto/blob/v.0.2/app/components/Microphone.js

NFC doesn't work at the moment: https://github.com/HSLdevcom/react-native-proto/blob/v.0.2/app/components/NFCTest.js

**Comment by 0is1** [comment]
So NFC reading started to work after I just installed and linked https://github.com/observ3r/nfc-ndef-react-native which is fork from [nfc-react-native](https://github.com/Lube/nfc-react-native) but we are actually using [react-native-nfc](https://github.com/Novadart/react-native-nfc) in the app at the moment. Seems legit...

https://github.com/HSLdevcom/react-native-proto/commit/fb7d2b5f1eaa60d295823d674e66735f70cfa42f

**Comment by 0is1** [comment]
There's now [demo survey in WebView](https://github.com/HSLdevcom/react-native-proto/commit/0c86a6fb4e82b76e132fb9a7742728650d11ab0a) that seems to work quite well except Android image upload, see: https://github.com/facebook/react-native/issues/5219

Luckily there's a PR https://github.com/facebook/react-native/pull/12807 but let's see when it's approved...
