### ISSUE TITLE
Move citybikes (and login) from toolbar into a menu

### ISSUE THREAD

**Issue by tuukka** [HSLdevcom/react-native-proto#26]

**Comment by 0is1** [comment]
I created "FakeSideMenu"-component that is used as a "menu" for now https://github.com/HSLdevcom/react-native-proto/commit/57723eb056e5536cc022252e20eff253344e6dda

If we want that the menu is more like for example: https://github.com/root-two/react-native-drawer or https://github.com/react-native-community/react-native-side-menu then we probably want to re-implement the whole navigation.
