### ISSUE TITLE
Bypass "Use location services" dialog

### ISSUE THREAD

**Issue by tuukka** [HSLdevcom/react-native-proto#27]
One possibility would be to add "?mock" to the URL, perform the geolocation request from the app code and feed the results into Digitransit by `window.mock.geolocation.setCurrentPosition(lat, lon)`.

**Comment by 0is1** [comment]
Is this already possible to do in Digitransit?

**Comment by tuukka** [comment]
Yes, that URL parameter and function are already implemented.

**Comment by 0is1** [comment]
If I understand correctly `?mock` is using always static location, see: http://github.com/HSLdevcom/digitransit-ui/blob/31a95008c967989cd62256be2c7c83caf635bd9e/app/action/MockActions.js#L12-L18

And that location is HSL-office. So there's no point to use this?

EDIT: nevermind, I misunderstood the point :)

**Comment by 0is1** [comment]
There's now implementation in `local-reittiopas-bundle`-branch
* https://github.com/HSLdevcom/react-native-proto/commit/7e101f860f93eb43e2307a9f88d124043f3741f2

But that branch can't be merged with master at the moment so I implemented it also to `<CustomWebView>`in master:
* https://github.com/HSLdevcom/react-native-proto/commit/e149d94dca7a0acf22f72313e90642d06c81e6b8
