### ISSUE TITLE
Investigate background services / tasks on Android

### ISSUE THREAD

**Issue by piuholo** [HSLdevcom/react-native-proto#39]
Currently the behaviour of the app varies between iOS and Android if the app is on background, inactive or killed.
This is especially the case with bluetooth monitoring/ranging and receiving push notifications while the phone is locked.

Android version could potentially benefit from running background tasks.

See resources:

https://facebook.github.io/react-native/docs/headless-js-android.html

https://github.com/vikeri/react-native-background-job

https://github.com/devfd/react-native-workers

**Comment by 0is1** [comment]
For geolocation bg: https://github.com/mauron85/react-native-background-geolocation

**Comment by 0is1** [comment]
[background-beacons branch](https://github.com/HSLdevcom/react-native-proto/tree/background-beacons) includes now quite well working implementation for Android. Biggest issue is maybe `backgroundSchedule` -> `period` that isn't running like defined with all Android versions. But reliability is still quite okay.

We also need to do extra ranging in there, see: http://github.com/HSLdevcom/react-native-proto/blob/e24edbd5ef29a9f5964498b0d7ae6b7885246ddc/index.js#L68-L89 but it seems that only Android 5.x is acting like that.

**Comment by 0is1** [comment]
Android background task is now merged to master, see `androidBackgroundJob`-function: http://github.com/HSLdevcom/react-native-proto/blob/0801ab727848501185b20529f1cb42d1bf27c560/index.js#L69-L104

The point is to start monitoring if there is `regionDidExit` / `regionDidEnter` event listener. If not add the event listeners, start monitoring and also start ranging. There's logic to stop the ranging (vehicle beacons at the moment) if phone doesn't see any beacons in 20 seconds. 

Main problem at the moment is that Android 6 and 7 doesn't stop ranging (even if the phone is sleeping) if there is beacon in range and your phone battery will be empty quite quickly.
