### ISSUE TITLE
Invoke HSL mobiililippu

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/react-native-proto#8]
1. Create Tab "osta lippuja", see mockups: https://projects.invisionapp.com/share/5K8VC8GTP#/screens/194934800

2. When user clicks on any of buttons open HSL mobiililippu

3. See if you can utilize any of these: https://github.com/HSLdevcom/shared-components

**Comment by 0is1** [comment]
If we want to use https://github.com/HSLdevcom/shared-components we need to create custom versions of the components, see: https://github.com/styled-components/styled-components#react-native

**Comment by samuliheljo** [comment]
I think we can discuss about this on thursday. For now, we can skip shared-components

**Comment by 0is1** [comment]
Styles are not yet implemented but functionality should be: https://github.com/HSLdevcom/react-native-proto/tree/mobile-ticket
