### ISSUE TITLE
Try out how beacons work with React Native

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/react-native-proto#9]
- Get familiar with react native bluetooth support
- Simple API: getRoute(): string[] -> Returns route names e.g. ['50','58']
- Try out whether we can build some heuristic that selects only "one vehicle route" based on beacon  "strength"

**Comment by tuukka** [comment]
Some example code for bluetooth beacons in react-native: https://github.com/stop2

**Comment by piuholo** [comment]
Both beacon monitoring and ranging work by using the module [https://github.com/MacKentoch/react-native-beacons-manager](url)

When ranging, for every beacon we can see 

- UUID
- Major
- Minor
- RSSI
- Proximity
- Accuracy 

Monitoring moving into the range of beacons broadcasting HSL's UUID can trigger enter/exit events. These events allow us to start ranging for a limited amount of seconds - even when the app is in background/inactive. While the app is on foreground we can do ranging continuously.

The signal strength of found beacons combined with a backend for resolving Major/Minor --> Individual vehicle, could be used to place the user in a single route/vehicle.

As there is a limit of how many regions ( = UUID or a combination of UUID + Major + Minor) we can monitor on iOS, 20 max, I'd suggest using 

- One single UUID for all HSL vehicles or vehicle types as region
- Major number for identifying the vehicle (limited to 65536)
- Minor number for identifying a single beacon (65536)
